---
name: build-image
on:
  push:
    branches:
      - main
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    runs-on: ubuntu-24.04
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build OCI container
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.rocm
          push: true
          build-args:
            - BASE_IMAGE="rocm/vllm-dev:navi_base"
            - BUILD_FA="0"
            - FX_GFX_ARCHS="gfx1100"
          tags: ghcr.io/michaelmnemonic/vllm:latest
        